version: '3'

services:
  mongodb:
    image: mongo:4.0
    ports:
      - 27027:27017
    volumes:
      - ../mongo/dump:/dump
    command: --replSet xpdays-2018
    restart: always
  
  mongodb-setup:
    image: mongo:4.0
    volumes:
      - ./scripts:/scripts
    restart: always
    entrypoint: [ "bash", "/scripts/mongodb-setup.sh" ]
